function calc() {
    var total = 0; //keeps track of total values
    var pork = document.getElementById("pork"); //each section gets the values from the menu and adds them to the total
    var porkQ = document.getElementById("porkQ");
    total += parseFloat(pork.value) * parseFloat(porkQ.value);
    var nacho = document.getElementById("nacho"); //example: this one is for nachos
    var nachoQ = document.getElementById("nachoQ");
    total += parseFloat(nacho.value) * parseFloat(nachoQ.value);
    var shrimp = document.getElementById("shrimp");
    var shrimpQ = document.getElementById("shrimpQ");
    total += parseFloat(shrimp.value) * parseFloat(shrimpQ.value);
    var texas = document.getElementById("texas");
    var texasQ = document.getElementById("texasQ");
    total += parseFloat(texas.value) * parseFloat(texasQ.value);
    var carabet = document.getElementById("carabet");
    var carabetQ = document.getElementById("carabetQ");
    total += parseFloat(carabet.value) * parseFloat(carabetQ.value);
    var chicken = document.getElementById("chicken");
    var chickenQ = document.getElementById("chickenQ");
    total += parseFloat(chicken.value) * parseFloat(chickenQ.value);
    var salmon = document.getElementById("salmon");
    var salmonQ = document.getElementById("salmonQ");
    total += parseFloat(salmon.value) * parseFloat(salmonQ.value);
    var soup = document.getElementById("soup");
    var soupQ = document.getElementById("soupQ");
    total += parseFloat(soup.value) * parseFloat(soupQ.value);
    var ice = document.getElementById("ice"); //example: this one is for ice cream
    var iceQ = document.getElementById("iceQ");
    total += parseFloat(ice.value) * parseFloat(iceQ.value);
    var apple = document.getElementById("apple");
    var appleQ = document.getElementById("appleQ");
    total += parseFloat(apple.value) * parseFloat(appleQ.value);
    var banana = document.getElementById("banana");
    var bananaQ = document.getElementById("bananaQ");
    total += parseFloat(banana.value) * parseFloat(bananaQ.value);
    var fruit = document.getElementById("fruit");
    var fruitQ = document.getElementById("fruitQ");
    total += parseFloat(fruit.value) * parseFloat(fruitQ.value);
    var coke = document.getElementById("coke");
    var cokeQ = document.getElementById("cokeQ");
    total += parseFloat(coke.value) * parseFloat(cokeQ.value);
    var margarita = document.getElementById("margarita");
    var margaritaQ = document.getElementById("margaritaQ");
    total += parseFloat(margarita.value) * parseFloat(margaritaQ.value);
    var wine = document.getElementById("wine");
    var wineQ = document.getElementById("wineQ");
    total += parseFloat(wine.value) * parseFloat(wineQ.value);
    var aperol = document.getElementById("aperol");
    var aperolQ = document.getElementById("aperolQ");
    total += parseFloat(aperol.value) * parseFloat(aperolQ.value);
    alert("Your total is " + Math.round(total * 100) / 100); //outputs the total
}